name: Build

on:
  push:
    branches:
      - master  # 你可以根据需要更改分支

jobs:
  generate-cover:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: 'Set up Node.js'
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Node Build
      run: |
        git config --global user.name "ryanuo"
        git config --global user.email "1577791638@qq.com"
        npm i
        npm run build
        npm run gh